version: "3.8"
services:
  localstack:
    build:
      context: ./docker/localstack
      dockerfile: Dockerfile
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - "./docker/localstack/init-queue.sh:/etc/localstack/init/ready.d/init-queue.sh"
